language: node_js

node_js:
  - 'stable'
  - '4'
  - '5'

sudo: false

before_install:
  - npm install -g typings
  - npm install -g codeclimate-test-reporter

after_script:
  - codeclimate-test-reporter < coverage/report-lcov/lcov.info
  - node_modules/.bin/coveralls < coverage/report-lcov/lcov.info

